services:
  lychie-back:
    image: node:current-alpine
    working_dir: /usr/src/app
    env_file:
      - path: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app/
    command: >
      sh -c "yarn install && yarn run dev"
